networks:   # this defines two different networks with different names that we can allow our services below access to
  frontend-network:
  backend-network:

secrets:    # makes certain files invisible except to the services that we specifically allow to see these secrets
  db_password:
    file: db_password.txt

services:
  backend:
    build: backend  # targets the listed directory as the location to find a Dockerfile to build from
    volumes:
      - "./config:/config"
      - "./backend/src:/code" # This allows us to change Python code while a container is running
                              # so we can debug and test on the fly.  A more modern solution for this specific
                              # use case would be to use Compose Watch (which the frontend uses), but since
                              # this is a personal project I'm leaving the volume here to get experience with it.
    secrets:
      - db_password
    networks:
      - frontend-network
      - backend-network
    ports:
      #- "5000:5000"  # makes API available via local brower for testing
      - "5678:5678"
    environment:  # sets environment variables
      - DEBUG=True    
    stop_signal: SIGINT # flask requires SIGINT to stop gracefully (default stop signal from Compose is SIGTERM)
    depends_on:   # won't start until db healthcheck returns true
      db:
        condition: service_healthy
    
  frontend: # currently this is all dev, do not use for prod
    build: frontend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      #VITE_BACKEND_URL: http://backend:5000 # was using this as a way to fetch from backend, now using vite.config.js
    stdin_open: true  # keep the container running and interactive
    tty: true         # keep the container running and interactive
    networks:
      - frontend-network
    depends_on:
      - backend
    develop:
      watch:  # enables Compose Watch to sync files from local to the container (don't use in prod)
        - action: sync
          path: frontend
          target: /app

  db: #NOTE: this is treated as the server/computer name
    image: postgres:13.22-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - backend-network
    ports:
      - "5432:5432"
    healthcheck:  # backend won't start until healthcheck succeeds
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

#  adminer:   # this was part of the example for postgres
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  db-volume:
